@extends('layouts.admin')

@section('title', 'Report Export History')
@section('page-title', 'Report Export History')

@section('content')
    <div class="space-y-6">
        <section class="rounded-3xl bg-slate-950 p-7 text-white">
            <h1 class="text-3xl font-black">
                Report Export History
            </h1>

            <p class="mt-2 text-sm text-slate-300">
                Audit record of CSV reports generated from the system.
            </p>
        </section>

        <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
            <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-slate-200 text-sm">
                    <thead class="bg-slate-50">
                        <tr>
                            <th class="px-5 py-4 text-left">Report</th>
                            <th class="px-5 py-4 text-left">Generated By</th>
                            <th class="px-5 py-4 text-left">Filename</th>
                            <th class="px-5 py-4 text-right">Rows</th>
                            <th class="px-5 py-4 text-left">Status</th>
                            <th class="px-5 py-4 text-left">Started</th>
                            <th class="px-5 py-4 text-left">Completed</th>
                        </tr>
                    </thead>

                    <tbody class="divide-y divide-slate-100">
                        @foreach ($exports as $export)
                            <tr>
                                <td class="px-5 py-4 font-bold">
                                    {{ $export->report_type->label() }}
                                </td>

                                <td class="px-5 py-4">
                                    {{ $export->generatedBy?->name ?? 'Deleted user' }}
                                </td>

                                <td class="px-5 py-4">
                                    {{ $export->filename }}
                                </td>

                                <td class="px-5 py-4 text-right">
                                    {{ number_format(
                                        $export->rows_exported
                                    ) }}
                                </td>

                                <td class="px-5 py-4">
                                    <span class="rounded-full px-3 py-1 text-xs font-bold ring-1 ring-inset {{ $export->status->badgeClasses() }}">
                                        {{ $export->status->label() }}
                                    </span>
                                </td>

                                <td class="px-5 py-4">
                                    {{ $export->started_at->format('d M Y, h:i A') }}
                                </td>

                                <td class="px-5 py-4">
                                    {{ $export->completed_at?->format('d M Y, h:i A') ?? '—' }}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            <div class="border-t border-slate-100 p-5">
                {{ $exports->links() }}
            </div>
        </section>
    </div>
@endsection